### ISSUE TITLE
Full-Text DB generation Error

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#16]
```
berdosierung', 1), ('Überdosierung/Intoxikationen', 1), ('Überempfindlichkeit', 1), ('ärztlichen', 1)]
Traceback (most recent call last):
  File "smartinfo.py", line 385, in <module>
    main(sys.argv[1:])
  File "smartinfo.py", line 320, in main
    soup_object = remove_html_tags(html_content)
  File "smartinfo.py", line 62, in remove_html_tags
    soup.find("div", {"class": "MonTitle"}).decompose()
AttributeError: 'NoneType' object has no attribute 'decompose'
```

**Comment by zdavatz** [comment]
https://github.com/zdavatz/fachinfo_ai

**Comment by zdavatz** [comment]
Seem like it is the Reg-Number: 63175, see: https://github.com/zdavatz/fachinfo_ai/blob/master/smartinfo.py#L319

**Comment by zdavatz** [comment]
The french Version crashes at the same place.
```
, ('élucidé', 1), ('élévation', 1), ('épidermique', 2), ('épidémiologiques', 1), ('érythémateuses', 1), ('étendu', 1), ('études', 2), ('évidence', 3), ('éviter', 1)]
Traceback (most recent call last):
  File "smartinfo.py", line 385, in <module>
    main(sys.argv[1:])
  File "smartinfo.py", line 320, in main
    soup_object = remove_html_tags(html_content)
  File "smartinfo.py", line 62, in remove_html_tags
    soup.find("div", {"class": "MonTitle"}).decompose()
AttributeError: 'NoneType' object has no attribute 'decompose'
```

**Comment by zdavatz** [comment]
run with: 
`/usr/local/bin/python3 smartinfo.py --lang=de`

**Comment by bettar** [comment]
it crashes at Baypress® regnr 46811, with xml of the "second" type
